version: "3"
services:
  coredns:
    image: coredns/coredns
    restart: always
    ports:
      - "53:53/udp"
    labels:
      - dns.host=core.dns.local
    environment:
      - UPSTREAM=8.8.8.8
    volumes:
      - "./coredns:/in"
    command: -conf /in/Corefile
  updater:
    build: .
    image: moredhel/dockerdns:1.0
    restart: always
    # privileged: true
    volumes:
      - "./coredns:/in"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - dns.host=scheduler.dns.local
    command: /app
